name: "CI"

on:
  create:
    tags:
      - "v*"

  workflow_dispatch:

jobs:
  build-images:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Find Release version"
        id: "find_release_version"
        run: "echo \"::set-output name=release_version::${GITHUB_REF#refs/tags/}\""
      - name: "Set up QEMU"
        uses: "docker/setup-qemu-action@v2"
      - name: "Set up Docker Buildx"
        uses: "docker/setup-buildx-action@v2"
      - name: "Login to DockerHub"
        uses: "docker/login-action@v2"
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: "Build and push Image"
        id: "build_push_image"
        uses: "docker/build-push-action@v3"
        env:
          RELEASE_VERSION: "${{ steps.find_release_version.outputs.release_version }}"
        with:
          file: "Dockerfile"
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_IMAGE }}:latest
            ${{ secrets.DOCKERHUB_IMAGE }}:${{ env.RELEASE_VERSION }}
